### PR TITLE
I did things

### PR DESCRIPTION
**Pull request by TentaRJ**
Fixed the compiling for macs thing stated in #10. There was just a `#if windows` in there, stopping compiling on other versions lmao!

### Also had the enemy gray notes go flashy flashy haha  :)

### CODE REVIEW

**Comment by brightfyregit** [comment]
Is the enemy note flashing code from Project FNF, or did you make it yourself?

**Comment by TentaRJ** [comment]
> Is the enemy note flashing code from Project FNF, or did you make it yourself?

The code for flashing enemy gray arrows was pulled from [this pull request on ninjamuffin99/Funkin](https://github.com/ninjamuffin99/Funkin/pull/571).

**Comment by brightfyregit** [comment]
Alright just checking lol

**Comment by TentaRJ** [comment]
> Alright just checking lol

Yeah I understand :)

**Review by haya3218 — APPROVED** [review]
looks good :)

**Pull request merged**
