### PR TITLE
Fix Build not working 

### PR DESCRIPTION
**Pull request by TheDrawingCoder-Gamer**
You guys removed the APIStuff file, which causes build to fail :grief: This edits the build file so it creates its own APIStuff file, without any keys.

### CODE REVIEW

**Comment by hdboye** [comment]
you have to create apistuff.hx yourself cuz it has api keys inside of it

**Comment by TheDrawingCoder-Gamer** [comment]
yeah, which is what this does.

**Comment by hdboye** [comment]
even if u put a lil empty one i suggest ppl just add it themselves as to not cause any local and remote repo conflicts for the dev

**Comment by hdboye** [comment]
they are using api keys so that needs to be hidden

**Review by hdboye — APPROVED** [review]
OH WAIT IM STUPID I DINDT READ WHAT THE FILE ACTUALLY DOES LOL YEAH U CAN MERGE THIS

**Comment by TheDrawingCoder-Gamer** [comment]
If you want the thing to still be able to connect properly try using secrets with github actions

**Comment by TheDrawingCoder-Gamer** [comment]
(which of course i can set up, but you'd have to do setup on repository end)

**Pull request merged**
